<?php

declare(strict_types=1);

namespace Workbench\App\Http\Controllers;

use Illuminate\Http\Client\ConnectionException;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Storage;
use Illuminate\View\View;
use Imsus\LaravelImgproxy\Enums\Format;
use Imsus\LaravelImgproxy\Enums\Gravity;
use Imsus\LaravelImgproxy\Enums\ResizeType;

/**
 * Renders the package playground: live URLs and images for a human reviewer.
 *
 * Every demo URL is generated by the real package and fetched by a local
 * imgproxy, so a reviewer sees the actual output, not mockups.
 */
final class PlaygroundController
{
    /**
     * The demo source URL: the workbench app's own /sample/blue-marble.jpg
     * (the "Blue Marble" photograph, NASA / Apollo 17, public domain).
     *
     * imgproxy runs in Docker, so the URL must be reachable from inside the
     * container. The default uses host.docker.internal, which Docker Desktop
     * resolves to the host; other Docker setups (e.g. Dory) need the host's
     * LAN IP instead — set PLAYGROUND_SOURCE in workbench/.env then. The
     * demos need no external image host: Wikimedia rate-limits hotlinking.
     */
    private function source(): string
    {
        return (string) config('laravel-imgproxy.source', 'http://host.docker.internal:8000/sample/blue-marble.jpg');
    }

    /**
     * @return array{configured: bool, source: string, instance: array{name: string, url: string, signed: bool, signature_size: int|null, encoding: string, health: int|null}, demos: list<array{label: string, description: string, url: string, note: string|null}>, presets: array{client: list<array{label: string, code: string, url: string}>, server: array{label: string, code: string, url: string, status: int|null}}, storage: array{public: string, private: string}}
     */
    public function __invoke(): View
    {
        $instance = $this->instance();
        $instance['health'] = $instance['url'] !== '' ? $this->health($instance['url']) : null;

        if ($instance['url'] === '') {
            return view('playground', [
                'configured' => false,
                'source' => $this->source(),
                'instance' => $instance,
                'demos' => [],
                'presets' => ['client' => [], 'server' => ['label' => '', 'code' => '', 'url' => '', 'status' => null]],
                'storage' => ['public' => '', 'private' => ''],
            ]);
        }

        return view('playground', [
            'configured' => true,
            'source' => $this->source(),
            'instance' => $instance,
            'demos' => $this->demos(),
            'presets' => $this->presets(),
            'storage' => $this->storageUrls(),
        ]);
    }

    /**
     * The imgproxy /health HTTP status, or null when unreachable.
     */
    private function health(string $baseUrl): ?int
    {
        try {
            return Http::timeout(2)->get(rtrim($baseUrl, '/').'/health')->status();
        } catch (ConnectionException) {
            return null;
        }
    }

    /**
     * The resolved default instance, summarized for the page header.
     *
     * @return array{name: string, url: string, signed: bool, signature_size: int|null, encoding: string}
     */
    private function instance(): array
    {
        $name = (string) config('laravel-imgproxy.default');
        $config = config("laravel-imgproxy.instances.{$name}");

        return [
            'name' => $name,
            'url' => (string) ($config['url'] ?? ''),
            'signed' => ($config['key'] ?? null) !== null && ($config['salt'] ?? null) !== null,
            'signature_size' => $config['signature_size'] ?? null,
            'encoding' => (string) ($config['encoding'] ?? 'base64'),
        ];
    }

    /**
     * The builder demos, each with its generated URL.
     *
     * @return list<array{label: string, description: string, url: string, note: string|null}>
     */
    private function demos(): array
    {
        $demos = [
            [
                'label' => 'Resize, quality, format',
                'description' => 'Fill 300×300, 80% quality, WebP output.',
                'builder' => imgproxy()->url($this->source())
                    ->resize(ResizeType::Fill, 300, 300)
                    ->quality(80)
                    ->format(Format::Webp),
                'note' => null,
            ],
            [
                'label' => 'Crop with gravity',
                'description' => 'Crop a relative 0.5×0.5 area anchored to the north edge, then fit 400×400.',
                'builder' => imgproxy()->url($this->source())
                    ->crop(0.5, 0.5, Gravity::North)
                    ->resize(ResizeType::Fit, 400, 400),
                'note' => null,
            ],
            [
                'label' => 'Effects',
                'description' => 'Width 600, gaussian blur 1.5, sharpen 0.5.',
                'builder' => imgproxy()->url($this->source())->width(600)->blur(1.5)->sharpen(0.5),
                'note' => null,
            ],
            [
                'label' => 'Zoom',
                'description' => 'Width 400 zoomed ×2 — renders 800px wide.',
                'builder' => imgproxy()->url($this->source())->width(400)->zoom(2),
                'note' => null,
            ],
            [
                'label' => 'Rotate and flip',
                'description' => 'Rotate 90° and flip vertically.',
                'builder' => imgproxy()->url($this->source())->rotate(90)->flip(vertical: true),
                'note' => null,
            ],
            [
                'label' => 'Focus point',
                'description' => 'Crop 0.5×0.5 and focus on (0.5, 0.2) — the vertical center, 20% from the top.',
                'builder' => imgproxy()->url($this->source())->crop(0.5, 0.5)->focusPoint(0.5, 0.2),
                'note' => null,
            ],
            [
                'label' => 'LQIP placeholder',
                'description' => 'A 16px blurred WebP of the same source — the blur-up preview used by the components.',
                'builder' => imgproxy()->url($this->source())->placeholder(),
                'note' => 'The placeholder goes in the src; the full image loads through the srcset (see the component demo).',
            ],
            [
                'label' => 'Raw escape hatch',
                'description' => 'A cache buster appended verbatim with raw(), unvalidated.',
                'builder' => imgproxy()->url($this->source())->raw('cb:playground-v1'),
                'note' => null,
            ],
        ];

        return array_map(
            fn (array $demo): array => [
                'label' => $demo['label'],
                'description' => $demo['description'],
                'url' => $demo['builder']->url(),
                'note' => $demo['note'],
            ],
            $demos,
        );
    }

    /**
     * The config preset demos, plus the imgproxy server-side preset path.
     *
     * @return array{client: list<array{label: string, code: string, url: string}>, server: array{label: string, code: string, url: string, status: int|null}}
     */
    private function presets(): array
    {
        $presets = [
            [
                'label' => 'thumb',
                'code' => "Imgproxy::url(\$source)->preset('thumb')->url()",
                'builder' => imgproxy()->url($this->source())->preset('thumb'),
            ],
            [
                'label' => 'hero',
                'code' => "Imgproxy::url(\$source)->preset('hero')->url()",
                'builder' => imgproxy()->url($this->source())->preset('hero'),
            ],
            [
                'label' => 'hero overridden',
                'code' => "Imgproxy::url(\$source)->preset('hero')->width(800)->url()",
                'builder' => imgproxy()->url($this->source())->preset('hero')->width(800),
            ],
        ];

        // imgproxy's own server-side presets (the pr: option) must be
        // registered on the server via IMGPROXY_PRESETS / IMGPROXY_PRESETS_PATH.
        // The local demo server has none, so this request fails — the expected
        // behavior until the server defines the preset.
        $serverBuilder = imgproxy()->url($this->source())->imgproxyPreset('sharp');

        return [
            'client' => array_map(
                fn (array $preset): array => [
                    'label' => $preset['label'],
                    'code' => $preset['code'],
                    'url' => $preset['builder']->url(),
                ],
                $presets,
            ),
            'server' => [
                'label' => 'imgproxy server preset',
                'code' => "Imgproxy::url(\$source)->imgproxyPreset('sharp')->url()",
                'url' => $serverBuilder->url(),
                'status' => $this->fetchStatus($serverBuilder->url()),
            ],
        ];
    }

    /**
     * The HTTP status imgproxy returns for the URL, or null when unreachable.
     */
    private function fetchStatus(string $url): ?int
    {
        try {
            return Http::timeout(5)->get($url)->status();
        } catch (ConnectionException) {
            return null;
        }
    }

    /**
     * The Storage macro output for a public and a private disk.
     *
     * Two local demo disks are wired at runtime so no cloud credentials are
     * needed: the public disk yields its url(), the private disk a pre-signed
     * temporaryUrl() from a fake signing callback.
     *
     * @return array{public: string, private: string}
     */
    private function storageUrls(): array
    {
        config(['filesystems.disks.playground-public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => 'http://127.0.0.1:8000/storage',
            'visibility' => 'public',
        ]]);

        config(['filesystems.disks.playground-private' => [
            'driver' => 'local',
            'root' => storage_path('app/private'),
        ]]);

        Storage::disk('playground-private')->buildTemporaryUrlsUsing(
            fn (string $path, $expiration, array $options = []): string => 'https://signed.example.com/'.$path.'?expires='.$expiration->getTimestamp(),
        );

        return [
            'public' => Storage::disk('playground-public')->imgproxy('sample.jpg')->url(),
            'private' => Storage::disk('playground-private')->imgproxy('sample.jpg')->url(),
        ];
    }
}
