<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Laravel imgproxy — playground</title>
    <style>
        :root {
            --border: #d8dee4;
            --muted: #59636e;
            --accent: #0969da;
            --bg: #f6f8fa;
        }

        * { box-sizing: border-box; }

        body {
            margin: 0;
            font: 15px/1.55 -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            color: #1f2328;
            background: #fff;
        }

        .wrap { max-width: 1100px; margin: 0 auto; padding: 24px 20px 64px; }

        header { border-bottom: 1px solid var(--border); margin-bottom: 24px; padding-bottom: 16px; }
        header h1 { margin: 0 0 4px; font-size: 22px; }
        header p { margin: 0; color: var(--muted); }

        .chips { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 12px; }
        .chip {
            font-size: 12px; font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
            padding: 3px 10px; border: 1px solid var(--border); border-radius: 999px; background: var(--bg);
        }
        .chip.ok { border-color: #1a7f37; color: #1a7f37; background: #f0fff4; }
        .chip.warn { border-color: #9a6700; color: #9a6700; background: #fff8c5; }

        section { margin-bottom: 32px; }
        section > h2 { font-size: 17px; margin: 0 0 12px; padding-bottom: 6px; border-bottom: 1px solid var(--border); }

        .notice {
            border: 1px solid #d4a72c; background: #fff8c5; border-radius: 6px;
            padding: 12px 16px; margin-bottom: 24px;
        }
        .notice code { background: rgba(9, 105, 218, 0.08); }

        .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(320px, 1fr)); gap: 16px; }
        .card { border: 1px solid var(--border); border-radius: 6px; padding: 14px; }
        .card h3 { margin: 0 0 4px; font-size: 14px; }
        .card p { margin: 0 0 10px; font-size: 13px; color: var(--muted); }
        .card .note { font-size: 12px; color: #9a6700; margin-top: 8px; }

        pre {
            background: var(--bg); border: 1px solid var(--border); border-radius: 6px;
            padding: 10px 12px; overflow-x: auto; font-size: 12px;
            font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
            margin: 0 0 10px; white-space: pre-wrap; word-break: break-all;
        }

        img.demo { display: block; max-width: 100%; height: auto; border: 1px solid var(--border); border-radius: 4px; }
        img.demo--placeholder { width: 300px; }
        img.source { max-width: 100%; height: auto; border: 1px solid var(--border); border-radius: 4px; }

        details { margin-top: 12px; }
        summary { cursor: pointer; font-size: 13px; color: var(--accent); }
        details pre { margin-top: 8px; }

        .two { display: grid; grid-template-columns: repeat(auto-fit, minmax(340px, 1fr)); gap: 16px; }
        .kv { font-size: 13px; }
        .kv dt { font-weight: 600; margin-top: 8px; }
        .kv dd { margin: 2px 0 0; }

        footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid var(--border); font-size: 12px; color: var(--muted); }
    </style>
</head>
<body>
<div class="wrap">
    <header>
        <h1>Laravel imgproxy — playground</h1>
        <p>Live review surface for <code>imsus/laravel-imgproxy</code> 2.0.0. Every URL below is generated by the real package and fetched by the configured imgproxy server.</p>
        <div class="chips">
            <span class="chip">instance: {{ $instance['name'] }}</span>
            <span class="chip">{{ $instance['url'] }}</span>
            @if ($instance['signed'])
                <span class="chip ok">signed (signature_size: {{ $instance['signature_size'] ?? 'full' }})</span>
            @else
                <span class="chip warn">unsigned (unsafe slot)</span>
            @endif
            <span class="chip">encoding: {{ $instance['encoding'] }}</span>
        </div>
    </header>

    @if (! $configured)
        <div class="notice">
            <strong>No imgproxy instance configured.</strong>
            Copy <code>workbench/.env.example</code> to <code>workbench/.env</code> and point
            <code>IMGPROXY_URL</code>, <code>IMGPROXY_KEY</code>, and <code>IMGPROXY_SALT</code> at a local imgproxy.
            The defaults match the Docker imgproxy used by the integration tests:
            <pre>docker run -d -p 8081:8080 \
  -e IMGPROXY_KEY=0000000000000000000000000000000000000000000000000000000000000000 \
  -e IMGPROXY_SALT=0000000000000000000000000000000000000000000000000000000000000000 \
  imgproxy/imgproxy</pre>
            Then restart the server with <code>composer serve</code>. The package works unsigned too — the
            <code>unsafe</code> slot is used when no key and salt are set.
        </div>
    @endif

    @if ($configured)
        <section>
            <h2>Source image</h2>
            <p>All demos use the same source, imgproxy's own test image (fetched by the imgproxy server, not the app):</p>
            <pre>{{ $source }}</pre>
            <img class="source" src="{{ $source }}" alt="The demo source image">
        </section>

        <section>
            <h2>URL builder</h2>
            <div class="grid">
                @foreach ($demos as $demo)
                    <div class="card">
                        <h3>{{ $demo['label'] }}</h3>
                        <p>{{ $demo['description'] }}</p>
                        <pre>{{ $demo['url'] }}</pre>
                        <img class="demo {{ str_contains($demo['label'], 'placeholder') ? 'demo--placeholder' : '' }}"
                             src="{{ $demo['url'] }}" loading="lazy" alt="{{ $demo['label'] }}">
                        @if ($demo['note'])
                            <p class="note">{{ $demo['note'] }}</p>
                        @endif
                    </div>
                @endforeach
            </div>
        </section>

        <section>
            <h2>Presets</h2>
            <p>Two distinct mechanisms — do not confuse them:</p>
            <ul style="font-size:13px;margin:0 0 12px">
                <li><strong>Client-side presets</strong> — named option sets defined in this package's config
                    (<code>workbench/config/laravel-imgproxy.php</code>), composed into the URL by <code>preset()</code>.
                    No imgproxy server configuration needed.</li>
                <li><strong>Server-side presets</strong> — defined on the imgproxy server itself
                    (<code>IMGPROXY_PRESETS</code> / <code>IMGPROXY_PRESETS_PATH</code>) and referenced with the
                    <code>pr:</code> option via <code>imgproxyPreset()</code>. The server must have the preset
                    registered, or it answers <code>500</code>.</li>
            </ul>
            <pre>'presets' => [
    'thumb' => ['resize' => 'fill', 'width' => 300, 'height' => 300],
    'hero'  => ['resize' => 'fill', 'width' => 1200, 'height' => 600, 'quality' => 85],
],</pre>
            <div class="grid">
                @foreach ($presets['client'] as $preset)
                    <div class="card">
                        <h3>{{ $preset['label'] }}</h3>
                        <pre>{{ $preset['code'] }}</pre>
                        <pre>{{ $preset['url'] }}</pre>
                        <img class="demo" src="{{ $preset['url'] }}" loading="lazy" alt="{{ $preset['label'] }}">
                    </div>
                @endforeach
            </div>
            <div class="grid" style="margin-top:16px">
                <div class="card">
                    <h3>{{ $presets['server']['label'] }}</h3>
                    <p>References a preset that must exist on the imgproxy server. The local demo server has none
                        registered, so this is expected to fail until it does:</p>
                    <pre>{{ $presets['server']['code'] }}</pre>
                    <pre>{{ $presets['server']['url'] }}</pre>
                    <p>
                        @if ($presets['server']['status'] === 200)
                            <span class="chip ok">imgproxy responded HTTP 200 — the preset is registered.</span>
                        @elseif ($presets['server']['status'] === null)
                            <span class="chip warn">imgproxy unreachable — status unknown.</span>
                        @else
                            <span class="chip warn">imgproxy responded HTTP {{ $presets['server']['status'] }} — the preset
                                is not registered on the server. Register it, e.g.
                                <code>IMGPROXY_PRESETS=sharp=sharpen:0.7</code>, then restart the container.</span>
                        @endif
                    </p>
                </div>
            </div>
        </section>

        <section>
            <h2>Blade components</h2>
            <div class="two">
                <div>
                    <h3 style="font-size:14px;margin:0 0 4px">&lt;x-imgproxy-img&gt;</h3>
                    <p style="font-size:13px;color:var(--muted);margin:0 0 10px">
                        Width-based srcset with an LQIP placeholder in the src, lazy loading, and class passthrough.
                    </p>
                    <x-imgproxy-img
                        src="{{ $source }}"
                        :widths="[320, 640, 1280]"
                        sizes="(min-width: 1024px) 50vw, 100vw"
                        preset="thumb"
                        placeholder
                        alt="Playground demo image"
                        class="demo"
                    />
                    <details>
                        <summary>Blade source</summary>
                        @verbatim
<pre>&lt;x-imgproxy-img
    src="{{ $source }}"
    :widths="[320, 640, 1280]"
    sizes="(min-width: 1024px) 50vw, 100vw"
    preset="thumb"
    placeholder
    alt="Playground demo image"
    class="demo"
/&gt;</pre>
                        @endverbatim
                    </details>
                </div>
                <div>
                    <h3 style="font-size:14px;margin:0 0 4px">&lt;x-imgproxy-picture&gt;</h3>
                    <p style="font-size:13px;color:var(--muted);margin:0 0 10px">
                        AVIF and WebP sources with a JPG fallback, each with its own srcset.
                    </p>
                    <x-imgproxy-picture
                        src="{{ $source }}"
                        :widths="[640, 1280]"
                        :formats="['avif', 'webp', 'jpg']"
                        sizes="100vw"
                        alt="Playground demo image"
                        class="demo"
                    />
                    <details>
                        <summary>Blade source</summary>
                        @verbatim
<pre>&lt;x-imgproxy-picture
    src="{{ $source }}"
    :widths="[640, 1280]"
    :formats="['avif', 'webp', 'jpg']"
    sizes="100vw"
    alt="Playground demo image"
    class="demo"
/&gt;</pre>
                        @endverbatim
                    </details>
                </div>
            </div>
        </section>

        <section>
            <h2>Storage</h2>
            <p>The <code>Storage::disk(...)->imgproxy($path)</code> macro: public disks yield the disk <code>url()</code>,
                private disks a pre-signed <code>temporaryUrl()</code>. The demo disks are wired locally — no cloud
                credentials — and the private disk uses a fake signing callback, so only the URL shapes are shown:</p>
            <dl class="kv">
                <dt>Public disk</dt>
                <dd><pre>Storage::disk('public')->imgproxy('sample.jpg')->url();</pre><pre>{{ $storage['public'] }}</pre></dd>
                <dt>Private disk</dt>
                <dd><pre>Storage::disk('s3')->imgproxy('sample.jpg')->url();</pre><pre>{{ $storage['private'] }}</pre></dd>
            </dl>
        </section>
    @endif

    <section>
        <h2>Artisan commands</h2>
        <pre>php artisan imgproxy:key
# IMGPROXY_KEY=...
# IMGPROXY_SALT=...

php artisan imgproxy:health
# The imgproxy instance [default] is healthy: HTTP 200.

php artisan imgproxy:health --instance=staging
# The imgproxy instance [staging] is healthy: HTTP 200.</pre>
    </section>

    <section>
        <h2>Validation</h2>
        <pre>composer test          # phpstan + pint + type coverage + pest
composer lint:check    # pint --test
composer analyse       # phpstan</pre>
        <p style="font-size:13px;color:var(--muted)">Live integration tests against a real imgproxy run when
            <code>IMGPROXY_URL</code>, <code>IMGPROXY_KEY</code>, and <code>IMGPROXY_SALT</code> are exported in the
            shell running <code>composer test</code>; they skip otherwise.</p>
    </section>

    <footer>
        Source image: imgproxy's own test data (test1.png). Generated with <code>composer build &amp;&amp; composer serve</code>.
    </footer>
</div>
</body>
</html>
